version: 0.0
os: linux
files:
  - source: sentimentAnalysisWebApp
    destination: ~/go/src/github.com/Nicolas-Constanty/sentimentAnalysisWebApp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
    - location: scripts/start_server
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300